# Generated by Django 3.2.5 on 2021-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalityquestion',
            name='type',
            field=models.CharField(default='positive', max_length=100),
            preserve_default=False,
        ),
    ]
