# Generated by Django 3.2.5 on 2021-10-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_personalityquestion_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testchoice',
            options={'ordering': ['?']},
        ),
    ]
