# Generated by Django 3.2.5 on 2021-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
    ]
