# Generated by Django 3.2.5 on 2021-10-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20211014_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='personality',
        ),
        migrations.AddField(
            model_name='applicant',
            name='a_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='c_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='e_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='n_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='o_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
