# Generated by Django 3.2.5 on 2021-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20211015_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='predicted_personality_type',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
