# Generated by Django 3.2.5 on 2021-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_applicant_predicted_personality_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='a_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='c_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='e_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='n_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='o_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
