# Generated by Django 3.2.5 on 2022-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20211015_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mbti_statement',
            field=models.CharField(default='None', max_length=1000000),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mbti_type',
            field=models.CharField(default='xxxx', max_length=100),
        ),
    ]
