# Generated by Django 3.2.5 on 2022-04-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220409_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='taken_mbti_test',
            field=models.BooleanField(default=False),
        ),
    ]
